/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './contexts/**/*.{js,ts,jsx,tsx}',
    './config/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './services/**/*.{js,ts,jsx,tsx}',
    './api/**/*.{js,ts,jsx,tsx}',
    './utils/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', '"Cascadia Code"', 'Consolas', 'monospace'],
        cyber: ['"Inter"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
      },
      colors: {
        at: {
          bg: '#0A0A0A',
          surface: '#151515',
          elevated: '#1C1C1C',
          subtle: '#111111',
          accent: '#D62828',
          'accent-hover': '#A31D1D',
          'accent-muted': 'rgba(214, 40, 40, 0.10)',
          text: '#F5F5F5',
          'text-secondary': '#DEDEDE',
          muted: '#999999',
          disabled: '#555555',
          border: 'rgba(255, 255, 255, 0.06)',
          'border-hover': 'rgba(255, 255, 255, 0.12)',
          'border-active': 'rgba(214, 40, 40, 0.4)',
        },
        sev: {
          low: '#22C55E',
          medium: '#EAB308',
          high: '#F97316',
          critical: '#EF4444',
          info: '#60A5FA',
        },
        st: {
          online: '#22C55E',
          offline: '#6B7280',
          warning: '#EAB308',
          error: '#EF4444',
        },
        cyber: {
          black: '#0A0A0A',
          dark: '#151515',
          cyan: '#D62828',
          purple: '#A31D1D',
          red: '#D62828',
          glass: 'rgba(21, 21, 21, 0.84)',
          grid: '#0A0A0A',
        },
      },
      backgroundImage: {
        'grid-pattern': 'linear-gradient(to right, rgba(255,255,255,0.04) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.04) 1px, transparent 1px)',
      },
      borderRadius: {
        card: '10px',
        btn: '8px',
        input: '8px',
        badge: '6px',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease-out',
        'fade-in-up': 'fadeInUp 0.3s ease-out forwards',
        'slide-in-right': 'slideInRight 0.25s ease-out',
        scan: 'scan 8s linear infinite',
        marquee: 'marquee 40s linear infinite',
        'scrolling-list': 'scrollingList 20s linear infinite',
        'vertical-scroll': 'verticalScroll 120s linear infinite',
      },
      keyframes: {
        scan: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100%)' } },
        fadeIn: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(16px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        scrollingList: { '0%': { transform: 'translateY(0)' }, '100%': { transform: 'translateY(-50%)' } },
        verticalScroll: { '0%': { transform: 'translateY(0)' }, '100%': { transform: 'translateY(-50%)' } },
      },
    },
  },
  plugins: [],
};
